version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/src/discord-bot"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
